### ISSUE TITLE
Way to avoid FOUC?

### ISSUE THREAD

**Issue by ethanmay** [felixdulfer/angular-iconic#1]
Been working with this library to load my iconic icons into my angular application. Love what you have so far, thanks for the work. I'm wondering if you have experienced flashes of un-styled content when working with this? In my current application, there is a brief amount of time before the icons have loaded in where the image references are broken. This happens, for instance, when I change from one state to the next. Do you have any ideas or recommendations to avoid this problem? Thanks again!

**Comment by felixdulfer** [comment]
This may be caused by the way that Iconic itself works. I suppose that `<img data-src="something">` will look like a broken image because it's not an `img` element with a proper `src` attribute. In fact, the `img` element will eventually be replaced by an `svg` element. So, the issue you are describing makes sense.

I believe the way to mitigate this is to hide the image until Iconic does its magic. Some basic CSS should do the trick:

```css
.iconic {
  opacity: 0;
}

.iconic.injected-svg {
  opacity: 1;
}
```

You may also want to set `width` and `height` properties to deal with any issues with content moving around the image while the page/state is loading.

Another way might be to just use the `src` attribute. This should work with this library and (Open)Iconic and would cause the browser to resolve the actual image, not think it is broken. But there might be another risk of a FOUC because the browser would maybe first load the un-styled image and then replace it with a styled image.

```html
<img src="/bower_components/open-iconic/svg/lock-locked.svg" 
     class="iconic" 
     alt="lock">
```

Please let me know if any of this is helpful.

**Comment by ethanmay** [comment]
Thanks so much for the reply @felixdulfer. That basic CSS was a good idea. It looks nice with a transition on the opacity too. It's not a big enough issue that I want to be adding src tags to all the images, just need it so the page doesn't look broken. Setting the width & height properties is also a good idea, I was doing that already to ensure the icons were taking up the proper spacing. This really seems like something the Iconic team should address. I may make a ticket over on their repo. Thanks again!

**Comment by felixdulfer** [comment]
Great to hear that the workaround yields the right results.
